---
- name: Enable PowerTools Repo
  #DNF Will not make it permanent
  shell: dnf config-manager --set-enabled PowerTools
  when:  (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")

- name: Installing Epel-Realese Package
  package:
    name: "epel-release"
    state: latest
  when:  (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")

- name: Update all packages in operating system
  async: 1
  poll: 0
  yum:
    name: "*"
    state: latest

- name: Rebooting servers
  include_role: 
    name: reboot_servers

- name: Installing base packages for Red Hat devices
  package:
    name: "{{ packages_RedHat }}"
    state: latest
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")
 
- name: Install base packages for Ubuntu devices
  package:
    name: "{{packages_Ubuntu}}"
    state: latest
  when: (ansible_distribution == "Ubuntu")

- name: Install VIRT packages for RH Hypervisors
  package:
    name: "{{ packages_virt_rh }}"
  when: 
    - "'hyper' in inventory_hostname" 
    - (ansible_distribution == "CentOS" or ansible_distribution == "RedHat")

- name: Install VIRT packages for Ubuntu Hypervisors
  package:
    name: "{{ packages_virt_ub }}"
  when: 
    - "'hyper' in inventory_hostname" 
    - (ansible_distribution == "Ubuntu")
  #tags:
  #  - virt_ub

- name: Enable and Start  tuned service
  systemd:
    name: tuned
    enabled: yes
    state: started

- name: Set Performance profile
  shell: tuned-adm profile "{{ tuned_profile }}"

- name: Restart tuned-adm to enable perfomance profile
  systemd:
    name: tuned
    state: restarted

- name: Update man pages
  shell: mandb

- name: Create local admin group
  group:
    name: admingroup
    state: present
    gid: 9000

#- include_vars: main.yml
- name: Create local admin accounts
  user:
    name: "{{ item.username }}"
    shell: /bin/bash
    groups: admingroup
    append: yes
  with_items: "{{ users }}"


- name: Rebooting Servers post Initial Setup
  include_role:
    name: reboot_servers

