- hosts: [centos]
  any_errors_fatal: false
  become_user: root
  become_method: sudo
  become: true
  connection: ssh


  roles:
    - facts
    - initial_setup
    #- reboot_servers
    #- base_install
    #- reboot_servers
