- hosts: [all]
  any_errors_fatal: false
  become_user: root
  become_method: sudo
  become: true
  connection: ssh


  roles:
    #- facts
    #- initial_setup
    - setup_admAccnts_ssh
    #- setup_webservers
    #- reboot_servers
    #- base_install
    #- reboot_servers
