- hosts: [all]
  any_errors_fatal: false
  become_user: root
  become_method: sudo
  become: true
  connection: ssh


  roles:
    - set_facts
    #- initial_setup
    #- setup_admAccnts_ssh
    - ad_integration
    #- harden_servers
    #- setup_webservers
    #- reboot_servers
    #- base_install
    #- reboot_servers
