packages_RedHat:
  - net-tools
  - expect
  - bind-utils
  - open-vm-tools
  - vim
  - oddjob
  - oddjob-mkhomedir
  - wget
  - screen
  - bc
  - sysstat
  - zip
  - unzip
  - rsync
  - screen
  - mutt
  - nc
  - telnet
  - xinetd
  - nfs-utils
  - autofs
  - chrony
  - lsof
  - facter
  - nrpe
  - tcpdump
  - tuned
  - tuned-utils
  - realmd
  - sssd 
  - oddjob
  - oddjob-mkhomedir 
  - adcli 
  - samba-common 
  - samba-common-tools 
  - krb5-workstation 
  - authselect-compat
  - NetworkManager-libnm
  - nm-connection-editor
  - python3-libsemanage
  - python3-policycoreutils

packages_Ubuntu:
  - net-tools
  - expect
  - open-vm-tools
  - vim
  - oddjob
  - oddjob-mkhomedir
  - wget
  - screen
  - bc
  - sysstat
  - zip
  - unzip
  - rsync
  - screen
  - mutt
  - telnet
  - xinetd
  - lsof
  - facter
  - tcpdump
  - tuned
  - tuned-utils
  - nfs-kernel-server
  - nfs-common
  - nagios-plugins
  - realmd 
  - libnss-sss 
  - libpam-sss 
  - sssd 
  - sssd-tools 
  - adcli 
  - samba-common-bin 
  - oddjob 
  - oddjob-mkhomedir 
  - packagekit

packages_virt_rh:
  - qemu-kvm 
  - libvirt
  - libvirt-python 
  - libguestfs-tools
  - virt-install

packages_virt_ub:
  - cpu-checker
  - qemu-kvm 
  - libvirt-daemon 
  - bridge-utils 
  - virtinst 
  - libvirt-daemon-system 
  - virt-top 
  - libguestfs-tools 
  - libosinfo-bin  
  - qemu-system 
  - virt-manager

