users:
  - username: koukla
  - username: cookie

packages_RedHat:
  - net-tools
  - bind-utils
  - open-vm-tools
  - vim
  - oddjob
  - oddjob-mkhomedir
  - wget
  - screen
  - bc
  - sysstat
  - zip
  - unzip
  - rsync
  - screen
  - mutt
  - nc
  - telnet
  - xinetd
  - nfs-utils
  - autofs
  - chrony
  - lsof
  - facter
  - nrpe
  - tcpdump
  - tuned
  - tuned-utils

packages_Ubuntu:
  - net-tools
  - open-vm-tools
  - vim
  - oddjob
  - oddjob-mkhomedir
  - wget
  - screen
  - bc
  - sysstat
  - zip
  - unzip
  - rsync
  - screen
  - mutt
  - telnet
  - xinetd
  - lsof
  - facter
  - tcpdump
  - tuned
  - tuned-utils
  - nfs-kernel-server
  - nfs-common
  - nagios-plugins
