---
- hosts: all
  tasks:
    - name: Create file
      file:
        path: /tmp/testfile_1
        state: touch
        owner: ansible
        group: ansible
        mode: 0755

    - name: Create a soft link to point to your original file
      file:
        src: /tmp/testfile_1
        dest: /var/tmp/testfile_1
        owner: ansible
        group: ansible
        state: link


